// Generated by CoffeeScript 1.7.1
(function() {
  var body, circle_fill, force_g, force_g_offsetX, force_g_offsetY, label_container, max_size, min_size, pack_g, pack_g_offsetX, pack_g_offsetY, pop_format, power_format, power_scale, rotate, stroke_fill, svg, wrap;

  body = d3.select("body");

  svg = d3.select("svg");

  min_size = 1;

  max_size = 300;

  circle_fill = "#f4f4f4";

  stroke_fill = "#DDDBDB";

  force_g_offsetX = 100;

  force_g_offsetY = 200;

  pack_g_offsetX = 450;

  pack_g_offsetY = 200;

  pop_format = d3.format(".3s");

  power_scale = d3.scale.pow().exponent(0.25).domain([0, 3000]).range([min_size, max_size / 2]);

  power_format = d3.format(".0f");

  force_g = svg.append("g").attr("transform", "translate(" + force_g_offsetX + ", " + force_g_offsetY + ")");

  pack_g = svg.append("g").attr("transform", "translate(" + pack_g_offsetX + ", " + pack_g_offsetY + ")");

  label_container = d3.select(".container").append("div").attr("class", "label-container");

  d3.json("data.json", function(err, data) {
    var ec_voter, ec_voter_power, force, force_data, force_labels, force_nodes, pack, pack_data, pack_root, pop_labels, pop_nodes, sectors_length, stage_style, update;
    ec_voter = data.election_comittee.voter;
    ec_voter_power = data.registered_voter / ec_voter;
    sectors_length = data.election_comittee.sectors.length;
    pack_root = {
      id: "all",
      name: "Registered Voter",
      value: data.registered_voter,
      power: 1,
      children: [
        {
          id: "others",
          name: "Others",
          value: data.registered_voter - ec_voter,
          power: 0
        }, {
          id: "ec-voters",
          name: "Voters for Election Comittee",
          value: ec_voter,
          power: ec_voter_power,
          children: []
        }
      ]
    };
    pack_root.children[1].children = data.election_comittee.sectors.map(function(sector) {
      return {
        id: sector.id,
        name: sector.name,
        value: sector.count,
        power: (ec_voter / sectors_length) / sector.count * ec_voter_power,
        children: [
          {
            id: "" + sector.id + "-cm",
            name: "Voted-in Election Comittee Members from " + sector.name,
            value: data.election_comittee.seats_per_sector,
            power: data.registered_voter / (data.election_comittee.seats_per_sector * sectors_length)
          }, {
            id: "" + sector.id + "-non-cm",
            name: "Election Comittee Non-members from " + sector.name,
            value: sector.count - data.election_comittee.seats_per_sector,
            power: 0
          }
        ]
      };
    });
    stage_style = {
      "stage1": [
        {
          id: "all",
          size: "big",
          fill: true,
          pop_label: "fit",
          power: true
        }
      ],
      "stage2": [
        {
          id: "all",
          size: "big",
          fill: false,
          pop_label: false,
          power: false
        }, {
          id: "others",
          size: "big",
          fill: false,
          pop_label: "fit",
          power: true
        }, {
          id: "ec-voters",
          size: "big",
          fill: true,
          pop_label: "fit",
          power: true
        }
      ],
      "stage3": [
        {
          id: "all",
          size: "big",
          fill: false,
          pop_label: false
        }, {
          id: "others",
          size: "big",
          fill: false,
          pop_label: "fit",
          power: true
        }, {
          id: "ec-voters",
          size: "big",
          fill: false,
          pop_label: false
        }, {
          id: "sector-lrw",
          size: "small",
          pop_label: {
            x: -120,
            y: -45
          },
          fill: true,
          power: true
        }, {
          id: "sector-hkcpb",
          size: "small",
          pop_label: {
            x: -145,
            y: -15
          },
          fill: true,
          power: true
        }, {
          id: "sector-ftit",
          size: "small",
          pop_label: {
            x: -110,
            y: 35
          },
          fill: true,
          power: true
        }, {
          id: "sector-ehil",
          size: "small",
          pop_label: {
            x: 85,
            y: 10
          },
          fill: true,
          power: true
        }, {
          id: "sector-lrw-cm",
          size: "small",
          pop_label: false
        }, {
          id: "sector-hkcpb-cm",
          size: "small",
          pop_label: false
        }, {
          id: "sector-ftit-cm",
          size: "small",
          pop_label: false
        }, {
          id: "sector-ehil-cm",
          size: "small",
          pop_label: false
        }
      ],
      "stage4": [
        {
          id: "all",
          size: "big",
          fill: false,
          pop_label: false
        }, {
          id: "others",
          size: "big",
          fill: false,
          pop_label: false,
          power: true
        }, {
          id: "ec-voters",
          size: "big",
          fill: false,
          pop_label: false
        }, {
          id: "sector-lrw",
          size: "small",
          pop_label: false,
          fill: false
        }, {
          id: "sector-hkcpb",
          size: "small",
          pop_label: false,
          fill: false
        }, {
          id: "sector-ftit",
          size: "small",
          pop_label: false,
          fill: false
        }, {
          id: "sector-ehil",
          size: "small",
          pop_label: false,
          fill: false
        }, {
          id: "sector-lrw-cm",
          size: "small",
          pop_label: {
            x: -130,
            y: -125
          },
          power: true
        }, {
          id: "sector-hkcpb-cm",
          size: "small",
          pop_label: {
            x: -145,
            y: -55
          }
        }, {
          id: "sector-ftit-cm",
          size: "small",
          pop_label: {
            x: -120,
            y: -5
          }
        }, {
          id: "sector-ehil-cm",
          size: "small",
          pop_label: {
            x: 65,
            y: -45
          }
        }
      ]
    };
    pack_g.datum(pack_root);
    pack = d3.layout.pack().size([max_size, max_size]);
    pack_data = pack.nodes(pack_root).filter(function(d) {
      return !d.hidden;
    });
    pop_nodes = pack_g.selectAll(".pop.node").data(pack_data).enter().append("g").attr("transform", function(d) {
      var cpoint, pt;
      cpoint = {
        x: max_size / 2,
        y: max_size / 2
      };
      pt = rotate(d, cpoint, -Math.PI / 2);
      d.pack_x = pt.x;
      d.pack_y = pt.y;
      return "translate(" + d.pack_x + ", " + d.pack_y + ")";
    }).attr("id", function(d) {
      return "pop-" + d.id;
    }).attr("class", function(d) {
      return "pop node " + d.id;
    });
    pop_nodes.append("circle").attr("r", function(d) {
      return d.r;
    });
    pop_labels = label_container.selectAll(".pack.label").data(pack_data).enter().append("div").attr("class", function(d) {
      return "pack label " + d.id;
    }).attr("id", function(d) {
      return "label-" + d.id;
    }).style("top", function(d) {
      return d.label_top = pack_g_offsetY + d.pack_y - d.r;
    }).style("left", function(d) {
      return d.label_left = pack_g_offsetX + d.pack_x - d.r;
    }).style("width", function(d) {
      return d.label_width = d.r * 2;
    }).style("height", function(d) {
      return d.label_height = d.r * 2;
    });
    pop_labels.append("p").html(function(d) {
      return "<strong>" + d.name + "</strong> " + (pop_format(d.value));
    });
    force_data = [];
    force_nodes = force_g.selectAll(".force.node").data(force_data);
    window.force = force = d3.layout.force().links([]).size([300, 300]).charge(function(d) {
      return -15 * d.force_r;
    }).on("tick", function(e) {
      force_nodes.attr("transform", function(d) {
        return "translate(" + d.x + ", " + d.y + ")";
      });
      return force_labels.style("-webkit-transform", function(d) {
        return "translate3d(" + (d.x + force_g_offsetX - d.force_r) + "px, " + (d.y + force_g_offsetY - d.force_r) + "px, 0px)";
      });
    });
    force_labels = label_container.selectAll(".power.label").data(force_data);
    window.update = update = function(stage) {
      var all, allx, ally, others, othersx, othersy, styles;
      styles = stage_style[stage];
      body.attr("class", stage);
      pop_nodes.style("opacity", 0);
      pop_labels.style("opacity", 0);
      d3.selectAll(".label-link").remove();
      force_data = [];
      styles.forEach(function(style) {
        data = pack_data.filter(function(d) {
          return d.id === style.id && style.power;
        });
        if (data.length) {
          data[0].style = style;
          force_data.push(data[0]);
        }
        pop_nodes.filter(function(d) {
          return d.id === style.id;
        }).style("opacity", 1).selectAll("circle").style("fill", function(d) {
          if (style.fill) {
            return null;
          } else {
            return "#FDFDFD";
          }
        });
        pop_labels.filter(function(d) {
          return d.id === style.id;
        }).style("width", function(d) {
          return d.label_width = typeof style.pop_label === "object" ? 100 : d.label_width;
        }).style("top", function(d) {
          if (typeof style.pop_label === "object") {
            return d.label_top + style.pop_label.y;
          } else {
            return d.label_top;
          }
        }).style("left", function(d) {
          if (typeof style.pop_label === "object") {
            return d.label_left + style.pop_label.x;
          } else {
            return d.label_left;
          }
        }).transition().duration(500).style("opacity", function(d) {
          if (style.pop_label) {
            return 1;
          } else {
            return 0;
          }
        });
        if (typeof style.pop_label === "object") {
          return pop_labels.filter(function(d) {
            return d.id === style.id;
          }).each(function(d) {
            var label_height;
            label_height = parseFloat(d3.select(this).style("height"));
            return pack_g.append("line").datum(d).attr("class", "label-link").attr("x1", function(d) {
              return d.pack_x;
            }).attr("y1", function(d) {
              return d.pack_y;
            }).attr("x2", function(d) {
              var offset;
              offset = style.pop_label.x > 0 ? -5 : d.label_width + 5;
              return d.label_left + style.pop_label.x - pack_g_offsetX + offset;
            }).attr("y2", function(d) {
              return d.label_top + style.pop_label.y - pack_g_offsetY + label_height / 2;
            });
          });
        }
      });
      others = pack_root.children[1];
      all = pack_root;
      othersx = others.x, othersy = others.y;
      allx = all.x, ally = all.y;
      all.x = all.px = othersx;
      all.y = all.py = othersy;
      others.x = others.px = allx;
      others.y = others.py = ally;
      force_nodes = force_nodes.data(force_data, function(d) {
        if (d.id === "all") {
          return "others";
        } else {
          return d.id;
        }
      });
      force_nodes.attr("transform", function(d) {
        return "translate(" + d.x + ", " + d.y + ")";
      }).select("circle").transition().duration(500).attr("r", function(d) {
        return d.force_r = power_scale(d.power);
      });
      force_nodes.exit().remove();
      force_nodes.enter().append("g").each(function(d) {
        delete d.px;
        delete d.py;
        delete d.x;
        return delete d.y;
      }).attr("id", function(d) {
        return "power-" + d.id;
      }).append("circle").attr("r", function(d) {
        return d.force_r = power_scale(d.power);
      });
      force_labels.remove();
      force_labels = label_container.selectAll(".power.label").data(force_data);
      force_labels.enter().append("div").attr("class", function(d) {
        return "power label " + d.id;
      }).attr("id", function(d) {
        return "label-" + d.id;
      }).style("width", function(d) {
        return d.force_r * 2;
      }).style("height", function(d) {
        return d.force_r * 2;
      }).append("p").html(function(d) {
        return "<strong>" + d.name + "</strong> " + (power_format(d.power)) + "x";
      });
      return force.nodes(force_data).start();
    };
    update("stage4");
    d3.select("button#stage1").on("click", function() {
      return update("stage1");
    });
    d3.select("button#stage2").on("click", function() {
      return update("stage2");
    });
    d3.select("button#stage3").on("click", function() {
      return update("stage3");
    });
    return d3.select("button#stage4").on("click", function() {
      return update("stage4");
    });
  });

  rotate = function(point, cpoint, angle) {
    var c, s, x, y;
    s = Math.sin(angle);
    c = Math.cos(angle);
    x = point.x - cpoint.x;
    y = point.y - cpoint.y;
    return {
      x: cpoint.x + x * c - y * s,
      y: cpoint.y + x * s + y * c
    };
  };

  wrap = function(text, width) {
    return text.each(function() {
      var dy, line, lineHeight, lineNumber, tspan, word, words, x, y, _results;
      text = d3.select(this);
      words = text.text().split(/\s+/).reverse();
      word;
      line = [];
      lineNumber = 0;
      lineHeight = 1.1;
      x = text.attr("x") || 0;
      y = text.attr("y") || 0;
      dy = parseFloat(text.attr("dy")) || 0;
      tspan = text.text(null).append("tspan").attr("x", x).attr("y", y).attr("dy", dy + "em");
      _results = [];
      while ((word = words.pop())) {
        line.push(word);
        tspan.text(line.join(" "));
        if (tspan.node().getComputedTextLength() > width) {
          line.pop();
          tspan.text(line.join(" "));
          line = [word];
          _results.push(tspan = text.append("tspan").attr("x", x).attr("y", y).attr("dy", ++lineNumber * lineHeight + dy + "em").text(word));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
  };

}).call(this);
